name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Version
        run: yarn version --new-version "${GITHUB_REF:11}" --no-git-tag-version

      - name: Publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
